version: '2'

networks:
  app-tier:
    driver: bridge

services:
  web:
    build: .
    command: connexion run swagger/recipes.yaml -v --debug
    depends_on:
      - rabbitmq
      - cassandra
    volumes:
      - ./src:/usr/src/app
    ports:
      - '5000:5000'

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - app-tier
    ports:
    - '5672:5672'
    - '15672:15672'

  cassandra:
    image: 'bitnami/cassandra:latest'
    networks:
      - app-tier
    ports:
      - '7000:7000'
      - '7001:7001'
      - '9042:9042'
      - '9160:9160'

#volumes:
#  application_src:
#    driver: host
#    driver_opts:
#      source: .\src