swagger: '2.0'
info:
  title: Hello API
  version: "0.1"
paths:
  /recipes/:
    get:
      operationId: api.recipes.get_recipes
      summary: Retrieves a list of recipes
      responses:
        200:
          description: Successful response.
          schema:
            type: array
            items:
              $ref: '#/definitions/Recipe'
    put:
      operationId: api.recipesupdate.create_recipe
      summary: Creates or updates a recipe
      consumes:
        - application/json
      parameters:
        - in: body
          name: recipe
          description: Recipe to create
          schema:
            $ref: '#/definitions/Recipe'
      responses:
        201:
          description: Creation has started


definitions:
  Recipe:
    type: object
    properties:
      id:
        type: string
        example: 'f8b05fa2-3b59-4e55-b4f8-978e0ad01d0c'
      name:
        type: string
        example: 'Chop Suey'